### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by SparrowKane** [IIInitiationnn/BloodEmporium#1]
Is there any way to speed up the time between selections?

**Comment by IIInitiationnn** [comment]
In the long-term, it would certainly be possible to implement certain predictive algorithms to speed up the selection process, and originally I was intending to include a "quick-select" mode which would not check for which nodes were consumed by the entity, making it slightly less accurate according to preferences, but much faster.

Unfortunately, since I have discontinued work on this, the idea did not come to fruition. I am possibly intending to return to this project in the coming months. Speeding up the selection will be a high priority.

In the meantime, it will definitely be slower than manual selection. The intended use case for the program in its current state is simply for AFK-ing while still being able to pick up what you want.

**Comment by IIInitiationnn** [comment]
Speed has been vastly improved with the new 1.0.0 update!
