### ISSUE TITLE
Unable to start program

### ISSUE THREAD

**Issue by dogteng** [IIInitiationnn/BloodEmporium#10]
Unable to start program，Used before

Prompt when using yesterday，Delete the file and decompress it again，Or error is prompted

An error occurred. Please check debug-22-11-1814-16-00.log for additional details.

-
![1](https://user-images.githubusercontent.com/118505844/202634686-bee9582e-85d9-4418-a1b9-4502f6e5794d.png)

**Comment by IIInitiationnn** [comment]
Can you please send the log file?

**Comment by dogteng** [comment]
> Can you please send the log file?
Sure，hope that it doesn't inconvenience you too much ，thk
[logs.zip](https://github.com/IIInitiationnn/BloodEmporium/files/10040286/logs.zip)

**Comment by IIInitiationnn** [comment]
I'm honestly not too sure, since it seemed to work once before not working again (according to your latest log), which I've never seen before. You can double check your settings (resolution, UI scale), and make sure you have no visual filters or shaders on. If your issue still persists, please send your `config.json` and a screenshot of your game with the bloodweb open.

**Comment by dogteng** [comment]
> I'm honestly not too sure, since it seemed to work once before not working again (according to your latest log), which I've never seen before. You can double check your settings (resolution, UI scale), and make sure you have no visual filters or shaders on. If your issue still persists, please send your `config.json` and a screenshot of your game with the bloodweb open.

It's ready to use. I deleted all the files and unzipped the setup program again. There's no problem. Thank you

**Comment by IIInitiationnn** [comment]
Please feel free to reopen this issue if you have problems in the future.
