### ISSUE TITLE
Character + Type filter options for preference profiles

### ISSUE THREAD

**Issue by Brok3nPix3l** [IIInitiationnn/BloodEmporium#13]
Not sure if this is intended, but combining a character e.g. "Artist" with a type e.g. "Perk" returns no results.
![image](https://user-images.githubusercontent.com/19913658/207117722-be6941f4-59df-4be9-a6a9-1bfa00f46b94.png)
![image](https://user-images.githubusercontent.com/19913658/207117732-fad1d1bf-39ec-47d5-aba8-d0b9ad5d7fbc.png)

This does work properly with "Survivor" and "Killer" character options however.
![image](https://user-images.githubusercontent.com/19913658/207118011-f71343cc-fe12-4b14-ae4e-d4fdfffb469d.png)
![image](https://user-images.githubusercontent.com/19913658/207118017-b3a7ee8c-42b2-436a-ab73-7f40da038b77.png)
![image](https://user-images.githubusercontent.com/19913658/207118147-0445c04a-7217-4330-84e3-ae7ae118efd0.png)
![image](https://user-images.githubusercontent.com/19913658/207118153-0f1a5e60-5840-409d-a5bf-493f88a61110.png)

It also correctly sorts the perks by character when that option is picked, so I feel like it knows which perk belongs to each character.

**Comment by IIInitiationnn** [comment]
This is intentional behaviour. Perks are intrinsically related to either killer or survivor, you can unlock them on the bloodweb for all survivors or killers. I understand that perks belong to certain characters, but this is currently designed to align with the bloodweb section of this app to avoid some confusion (selecting the Nurse for example will still allow all killer perks to be selected on the bloodweb, not just Nurse perks). I assume that most, if not all users have some subset of items, perks, addons etc. that they are oriented to work towards on the bloodweb, so I hope this shouldn't be a problem. Please feel free to let me know your thoughts if you disagree.

**Comment by Brok3nPix3l** [comment]
Thanks for responding! That reasoning makes sense and it's clear I hadn't considered the use case of "if I'm playing as x killer, I want to make sure it prioritizes these add-ons". My initial use case was to set a subtier for each of a character's shared perks based on how good that character is (subjective) so as to prioritize buying perks from weaker characters as I work towards prestiging all of the characters (from strongest to weakest) and ultimately get all of the perks on each of the characters a little bit quicker (maybe even before everyone is P3).
