### ISSUE TITLE
An error Unable to run

### ISSUE THREAD

**Issue by jlhsr** [IIInitiationnn/BloodEmporium#19]
initialisation, merging
capturing screen
matched origin: origin_basic_black.png
vector: circles and match to unlockables
Traceback (most recent call last):
  File "state.py", line 143, in run
  File "matcher.py", line 78, in vector_circles
  File "matcher.py", line 98, in get_circle_properties
cv2.error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\imgproc\src\hough.cpp:2253: error: (-215:Assertion failed) !_image.empty() && _image.type() == CV_8UC1 && (_image.isMat() || _image.isUMat()) in function 'cv::HoughCircles'

**Comment by jlhsr** [comment]
[config.txt](https://github.com/IIInitiationnn/BloodEmporium/files/10411211/config.txt)

**Comment by IIInitiationnn** [comment]
This error generally occurs because the app is not detecting your bloodweb. Please ensure your resolution and UI scale are correct and that you have saved these settings. If you have multiple monitors, try swapping the game to your primary monitor.
If you are still having issues, please send a fullscreen screenshot of your game with any bloodweb open.
