### ISSUE TITLE
Some problems I get

### ISSUE THREAD

**Issue by TyokPlex** [IIInitiationnn/BloodEmporium#36]
1st - When I import my config file to the new version the background colors of the perks disappear for some reason, but default config file does not happen

2nd - When I donwload the last version from the launcher it doesn't download anything, only the change the name of the exe

3rd - Some times when I use the app and take some items from the bloodweeb after reach the last... 5 o less items it pause for 4 seconds idk why

4th - Not happen to much but sometimes when it try to get a blocked item from bloodweeb it continues try to get the item indefinitely, I must stop the app and run again

Last of all, I love this app, I will try to give you feedback of everything I get.

Cheer up.

**Comment by IIInitiationnn** [comment]
1. Check the path in your settings. If it is set to a folder where there are icons (e.g. if you have default icons from DBD Icon Toolbox) you may have issues. Either way, compare the paths between your two configs and see what's different.
2. This is a known issue, currently investigating a fix.
3. The app probably thinks it completed a level when there were still items remaining. The AI model isn't perfect so that's the unfortunate downside, but I'm always working on improving the accuracy!
4. Also an issue with accuracy, will keep working on it.

Really appreciate the feedback! Your input is greatly valued, please let me know if you run into further issues :)

**Comment by TyokPlex** [comment]
For the 1st issue, I will give u my file, I compare both and dont see the problem, I cant see the color background of the icons in the app
[config.zip](https://github.com/IIInitiationnn/BloodEmporium/files/11304439/config.zip)

**Comment by IIInitiationnn** [comment]
Your config has the path set to
`D:/Program Files/Steam/steamapps/common/Dead by Daylight/DeadByDaylight/Content/UI/Icons`
but the default path is
`C:/Program Files (x86)/Steam/steamapps/common/Dead by Daylight/DeadByDaylight/Content/UI/Icons`
You will need to set your path in settings to either this default path, or a random empty folder.

**Comment by TyokPlex** [comment]
Its fix with a random empty folder, thanks.

Now waiting for a new update, I'm starting to need it a lot jajaja.
