### ISSUE TITLE
Killer Addons 7.3.0 Update

### ISSUE THREAD

**Issue by FlamingFox911** [IIInitiationnn/BloodEmporium#43]
Otz recently released a new infographic showcasing the tiers of all killer addons.
![ALL_ADDONS_V4](https://github.com/IIInitiationnn/BloodEmporium/assets/11638944/4e573f5c-dba4-480b-9b98-b7910233783e)
This means that a (potential) update to the Otz profiles would be required.

**Comment by FlamingFox911** [comment]
Here is a more appropriate graphic for actual purchase priority (and updated for 7.3.0)
![ADDON_REFERENCE_GUIDE_V3](https://github.com/IIInitiationnn/BloodEmporium/assets/11638944/8df82c58-628c-4d13-b1ce-a3d7e2ab14a3)

**Comment by IIInitiationnn** [comment]
By the time patch 7.4.0 rolls around in a couple days, I will try to have these profiles updated. Thanks for your patience!

**Comment by IIInitiationnn** [comment]
Otz has updated the add-on infographic for 7.4.0.
I have attached the updated 7.4.0 presets ([ignores perks](https://cdn.discordapp.com/attachments/1016477968220037201/1189470697165160478/otzs_tier_list_ignores_perks.emp), [prioritises perks](https://cdn.discordapp.com/attachments/1016477968220037201/1189470697542656010/otzs_tier_list_prioritises_perks.emp)) for any users who may need it.

Note: I am opting not to update the app yet for such an insignificant change (due to the inefficiency of the current auto-installer which needs to redownload and reinstall the entire ~1gb app), so this config will not be available by default in the latest version of the app (v1.2.2). However, whenever v1.2.3 is released (e.g. with the next content drop), the bundled config will indeed be up to date with 7.4.0.

Once again, thanks for your patience.

**Comment by IIInitiationnn** [comment]
Otz tier list profiles have now been updated in [v1.2.3](https://github.com/IIInitiationnn/BloodEmporium/releases/tag/v1.2.3).
