### ISSUE TITLE
Prolonged and/or repeated alt-tab breaks hotkey.

### ISSUE THREAD

**Issue by FlamingFox911** [IIInitiationnn/BloodEmporium#50]
During the event, I have been farming up points then using this program to spend them. Eventually, the command to run/terminate (left on default of Ctrl + Alt + 9) would no longer work.

**Comment by IIInitiationnn** [comment]
I've noticed this issue in my own usage over the last while but haven't been able to identify the root cause. For now as a temporary workaround, you can press Ctrl + Alt + Del to enter a menu which should forcibly terminate the bloodweb process. From there, you can restart Blood Emporium and the hotkey should resume working. Thanks for the report, I will continue investigating and update this issue accordingly.

**Comment by IIInitiationnn** [comment]
I have found a potential cause for this problem and fixed it for an upcoming update. For now, I will be marking this issue as resolved.
After the next update (which will be v1.2.10), if you still find you are having this problem, please feel free to leave another comment.
