### ISSUE TITLE
Wrong items being bought

### ISSUE THREAD

**Issue by reithegoat** [IIInitiationnn/BloodEmporium#52]
Upon selecting a saved custom profile and starting the program, it picks other items it should not be selecting.

https://github.com/user-attachments/assets/12150109-46e2-4d6e-97ee-ab3a6d5b57e5

[cake and streamers only.zip profile file](https://github.com/user-attachments/files/16450656/cake.and.streamers.only.zip)

**Comment by IIInitiationnn** [comment]
It appears you have shaders / visual filtering enabled on your game, which may be causing the app to recognise items incorrectly. If this does not fix the issue, try setting the tiers of cakes to be higher. If this still does not work, please send me the relevant log files from the `log` folder of the Blood Emporium installation so I can investigate the cause of the problem.

**Comment by IIInitiationnn** [comment]
The bloodweb you have shown in the video does not contain any cakes or streamers. The intention of the program is to automatically collect items from the bloodweb, favouring the items available with high preference values. It will not terminate when a desired item is not found.
I am also noticing you have some kind of visual shaders or colourblind mode; I would recommend switching this off when running the program for better accuracy.

**Comment by reithegoat** [comment]
> The intention of the program is to automatically collect items from the bloodweb, favouring the items available with high preference values. It will not terminate when a desired item is not found.

I understand that. However, there's the Auto-Purchase Threshold function that is what I use to automate when there's no favored items.

> I am also noticing you have some kind of visual shaders or colourblind mode

I have completely forgotten to disable that before running the program. My mistake. Thank you for pointing that out.

**Comment by IIInitiationnn** [comment]
Hey! Sorry for the overdue response, I assumed this was resolved since it was closed.
If this is still relevant for you, please note that the auto-purchase threshold specifies that only items that are strictly BELOW the specified threshold will be purchased (not inclusive). For your usage, that will mean setting the threshold to at least tier 0, subtier 1, so that all neutral items (which have tier 0 and subtier 0) will be considered for auto-purchase.

The idea behind the threshold settings is that you can simply set it to the lowest value of your desired items. In your case, your least desired items are the Survivor Pudding and Escape Cake, with tier 1 and subtier 1. Setting this as the threshold will ensure that any unlockables below this (but NOT including the Pudding and Cake) will be auto-purchased (though of course setting it to tier 0 subtier 1 as mentioned above will apply the same behaviour for your situation).
