### ISSUE TITLE
Automatically detect current Character

### ISSUE THREAD

**Issue by femboyfin** [IIInitiationnn/BloodEmporium#55]
It would be really convenient if there was an option to automatically detect the current Character based on the name shown above the current bloodweb level.

**Comment by IIInitiationnn** [comment]
This has been suggested in the past, but due to the implementation effort required to simply reduce one click on the user's end, I have opted to not implement this feature. This includes handling the many different languages and ensuring optimal accuracy to prevent runtime errors. Future work with OCR will more likely revolve around reading the user's bloodpoints (instead of using an estimate, as it currently is), since this is a more functionally useful feature for the user.
Nevertheless, I am grateful for the suggestion and hope you can understand why I will not be going forward with developing this.

**Comment by femboyfin** [comment]
That all makes sense, thanks for the quick reply and taking the time to explain! ❤️
